### PR TITLE
Lowering registry permission asked by FFViper.exe

### PR DESCRIPTION
**Pull request by PlutoniumHeart**
Sorry, I accidently pushed to the master branch in my home computer...
Signed-off-by: PlutoniumHeart zhitaoli.hust@gmail.com

### CODE REVIEW

**Comment by vinnydiehl** [comment]
Woah woah woah, if you accidentally commit to master, `git reset` it, don't push it to central... : P

I fixed master, but it'll mess up your history for that branch. Doesn't really matter though because nobody should really touch master, but if you want it set straight just delete the branch and fetch it again.

**Comment by PeterMeyer** [comment]
Be carefully with the Registry stuff! You should allways check if Theatre Switching is working, because it depends right now on the Registry. For FF8 we can project remving this but if Theatreswitching is brake this would be no good one!
Allways be carefull about 32 bit and 64 Bit Registry. Some Parts of 64-Bit only Registry will not run on 32-Bit  Windows Machines.

**Comment by vinnydiehl** [comment]
Yeah, theatre switching is the biggest reason that I can't rip out all of the registry code. I'm going to change this when I change how writable config files are stored.

**Comment by PeterMeyer** [comment]
This should be done in FF8 We need an stable FF7 build for the todays Databases. They need this stuff. Also the 3rd Party Buildtools. This will be longer mission. It has also a lot todo with the Component Object Modell (COM) and on top of com resides MFC and DirectX and Networking. This has to be planned i think. Be verry carefull, its easy to remove but    it has unwanted sideeffects for sure.I think before we can really remove this, we need and new Scenegraph Subproject GLEngine (parallel to the now working DXEngine) wich has no dependencies to COM/ActiveX/DirectX/MFC/Registry/ATL and Win32.

**Pull request merged**
