### PR TITLE
I have found a low-level read routine overridden by the original Falcon ...

### PR DESCRIPTION
**Pull request by PlutoniumHeart**
...4.0 developers.

Probably at their time this low-level read routine was not included in the VS's library,
but now it is, and the old one is not working, thus causing Issue #1, I comment it out,
it seems to be working.
I also commented out a line in "TexBank.cpp" which sets the "maxCompressedSize" to 0xffffffff
causing the following new comand to fail.
The application still having problems at this point, the problem seem to be located in
"DrawParticleSys.cpp" the function "bool DrawableParticleSys::LoadParameters(void)"
I am not quite familar with DirectX stuff, so I am going to leave it to you guys at the
moment.

I have found a low-level read routine overridden by the original Falcon 4.0 developers.
Probably at their time this low-level read routine was not included in the VS's library,
but now it is, and the old one is not working, thus causing Issue #1, I comment it out,
it seems to be working.
I also commented out a line in "TexBank.cpp" which sets the "maxCompressedSize" to 0xffffffff
causing the following new comand to fail.
The application still having problems at this point, the problem seem to be located in
"DrawParticleSys.cpp" the function "bool DrawableParticleSys::LoadParameters(void)"
when the while loop goes into "On("size"){}" part.
I am not quite familar with DirectX stuff, so I am going to leave it to you guys at the
moment.

Plutonium

Signed-off-by: Plutonium zhitaoli.hust@gmail.com

### CODE REVIEW

**Comment by vinnydiehl** [comment]
Thanks a lot @PlutoniumHeart. :+1: Not sure what happened as the diff was massive, but I weeded everything out and condensed it all into a smaller commit into the main tree and gave you credit there.

Don't be afraid to remove code, by the way- the code is under version control, so always delete before committing instead of leaving it commented out.

Now have a lolly, you earned it. :lollipop:

**Comment by PlutoniumHeart** [comment]
@gbchaosmaster I made few changes only, majority of the diff was because I added the include and lib for the Directx 8 so that I can compile the code. Not sure why the original code doesn't include those. 
I also mentioned that there is subsequent bug in the DirectX part of the code, which I may not be able to help out, hopefully you guys are good at DirectX.

**Comment by vinnydiehl** [comment]
@PlutoniumHeart This can be configured within Visual Studio's options without requiring an environment variable in Windows or littering the code with said EV. The README explains how to set that up in your user options.

The next bug is a weird array overflow, I hacked it away but I fear that that might cause problems so I'm looking deeper into it.

**Comment by PlutoniumHeart** [comment]
@gbchaosmaster Were you able to get in the game by doing that? And the link for the tutorial is actually the download link for DirectX8 SDK.

**Comment by vinnydiehl** [comment]
@PlutoniumHeart

> [This tutorial](http://www.darwinbots.com/numsgil/dx81sdk_full.exe) covers how to do that- follow the instructions under "Setting up the Include and Library Paths", you can ignore "Linking the DirectX Static Libraries In Your Projects" as that is already taken care of.

And nope, there's a whole line of problems that need to be tackled one-by-one. :trollface:

**Comment by PeterMeyer** [comment]
Awsome! 
The Env Variable for Direct X is a esay one. You just have to register a Windows Environment Variable with the
Name DX81_SDK wich should simply point to the Folder where you have unzipped the DXSDK81 Archive.
You can check this with: echo %DX81_SDK% on the Windows Command line prompt (cmd.exe) if it returns
the patch to the DirectX Folder anything is done and good. In Visual Studio the DirectX Lib and include folder can
now be found using $(DX81_SDK)I/nclude or $DX81_SDK)l/lib instead of hardcoded or special path settings in VS
itself. But DirectX will be removed as soon as possible, so we need it not for a long time.

**Pull request closed without merging**
