### PR TITLE
Many small fixes

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
Small German fix

**Comment by ghost** [comment]
Many fixes to camel case and variable names

**Comment by vinnydiehl** [comment]
This was getting pretty massive so I condensed a lot of this. The latest work, with (most) of these changes, is available in the [danny-fixes](https://github.com/FreeFalcon/freefalcon-central/commits/feature/danny-fixes) branch.

Only things that I knocked out were the include organization because it seemed to wreak absolute havoc with all of the changes that were being done to WinMain, I'll fix this later, and the variable name changes as some of them are less than beneficial or [out-of-style](https://github.com/FreeFalcon/docs/blob/master/standards/syntax.md). A few in particular that I don't agree with:
- It's called a directory, not a folder
- Maybe some light Hungarian notation for pointers, but the whole word Pointer gets a bit cumbersome

I do agree, however, that a lot of the useless Hungarian notation (g_b prefixes, etc.) have to go, but this should be done by completely restructuring how global config variables are handled. Either way they aren't essential changes and we'll focus on making the entire code adhere to one naming style once we have a more working project, as we discussed via email.

I'm not merging this into develop yet simply because I haven't tested whether or not my consolidations fucked up everything. If there's anything to be fixed on the new branch, feel free. I'll leave this open for now. I'll deal with integrating your changes in the other pull request into the branch as soon as I get the time.

I'll touch on some other things later, I gotta run right now.

**Comment by ghost** [comment]
No need to use this, I have started over in a new branch.
This branch can be deleted.

**Pull request closed without merging**
